name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download ViennaRNA release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: ViennaRNA/ViennaRNA
          tag: v2.6.4

      - name: Unpack ViennaRNA release
        run: unzip ViennaRNA-2.6.4.zip

      - name: Run configure
        run: |
          cd ViennaRNA-2.6.4
          pwd
