name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download wrapper library source
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CSource
        
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: ViennaRNA/ViennaRNA
          tag: v2.6.4

      - name: Unpack ViennaRNA release
        run: unzip -q ViennaRNA-2.6.4.zip

      - name: Run configure
        run: |
          cd ViennaRNA-2.6.4
          ./configure --prefix=$PWD/build --without-perl --without-python --without-swig --without-doc-html --without-doc-pdf --without-doc --enable-shared=yes --enable-static=no --enable-universal-binary=yes

      - name: Run make
        run: |
          cd ViennaRNA-2.6.4
          make

      - name: Run make install
        run: |
          cd ViennaRNA-2.6.4
          make install

      - name: Build wrapper library
        run: |
          ls
          echo "test"
          ls build
          
          clang++ CSource/wrapper.c --shared -Wl,--whole-archive,$PWD/build/lib/libRNA.a -Wl,--no-whole-archive -o libRNA.so

      - uses: actions/upload-artifact@v4
        with:
          name: linux-library
          path: libRNA.so

  
  build-macos:
    runs-on: macos-latest
    
    steps:
      - name: Download wrapper library source
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CSource
      
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: ViennaRNA/ViennaRNA
          tag: v2.6.4

      - name: Unpack ViennaRNA release
        run: unzip -q ViennaRNA-2.6.4.zip

      - name: Run configure
        run: |
          cd ViennaRNA-2.6.4
          ./configure --prefix=$PWD/build --without-perl --without-python --without-swig --without-doc-html --without-doc-pdf --without-doc --enable-shared=yes --enable-static=no --enable-universal-binary=yes

      - name: Run make
        run: |
          cd ViennaRNA-2.6.4
          make

      - name: Run make install
        run: |
          cd ViennaRNA-2.6.4
          make install

      - name: Build wrapper library
        run: |
          clang++ CSource/wrapper.c --shared -Wl,-force_load,$PWD/build/lib/libRNA.a -o libRNA.dylib

      - uses: actions/upload-artifact@v4
        with:
          name: macos-library
          path: libRNA.dylib


  build-windows:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            unzip
            gcc
            make
            mpfr-devel
            gmp-devel

      - name: Download wrapper library source
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CSource
  
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: ViennaRNA/ViennaRNA
          tag: v2.6.4

      - name: Unpack ViennaRNA release
        shell: msys2 {0}
        run: unzip -q ViennaRNA-2.6.4.zip
  
      - name: Run configure
        shell: msys2 {0}
        run: |
          cd ViennaRNA-2.6.4
          ls
          mkdir build
          ./configure CFLAGS="-std=gnu17" CXXFLAGS="-std=gnu++17" --prefix=$PWD/build --without-perl --without-python --without-swig --without-doc-html --without-doc-pdf --without-doc --enable-shared=yes --enable-static=no --without-kinfold --enable-universal-binary=yes --disable-pthreads --disable-openmp LDFLAGS="-lwinmm"
  
      - name: Run make
        shell: msys2 {0}
        run: |
          cd ViennaRNA-2.6.4
          make -C src/ViennaRNA
  
      - name: Run make install
        shell: msys2 {0}
        run: |
          cd ViennaRNA-2.6.4
          make -C src/ViennaRNA install

      - name: Build wrapper library
        shell: msys2 {0}
        run: |
          mkdir wrapper_build
          
          # Copy dependencies to build directory
          cp /usr/bin/msys-mpfr-6.dll wrapper_build
          cp /usr/bin/msys-2.0.dll wrapper_build
          cp /usr/bin/msys-gcc_s-seh-1.dll wrapper_build
          cp /usr/bin/msys-stdc++-6.dll wrapper_build
          cp /usr/bin/msys-gmp-10.dll wrapper_build

          # Build the wrapper
          g++ CSource/wrapper.c -shared -Wl,--whole-archive,$PWD/ViennaRNA-2.6.4/build/lib/libRNA.a -Wl,--no-whole-archive -lwinmm -lws2_32 -lpthread -lmpfr -lgmp -o wrapper_build/libRNA.dll

          # Check that the dependencies are included
          ldd wrapper_build/libRNA.dll

      - uses: actions/upload-artifact@v4
        with:
          name: windows-library
          path: wrapper_build/


  final-assembly:
    name: Final paclet assembly
    
    needs:
    - build-linux
    - build-macos
    - build-windows
    
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
      with:
        path: ViennaRNALink
        sparse-checkout: |
          Kernel
          Documentation
          PacletInfo.wl
          ResourceDefinition.nb
    
    - name: Download macOS builds
      uses: actions/download-artifact@v4
      with:
        name: macos-library
        path: ViennaRNALink/LibraryResources/MacOSX-ARM64/

    # Unclear if this version of the library can actually work on x86 macs
    - name: Download macOS x86 builds
      uses: actions/download-artifact@v4
      with:
        name: macos-library
        path: ViennaRNALink/LibraryResources/MacOSX-x86-64/
        
    - name: Download Linux builds
      uses: actions/download-artifact@v4
      with:
        name: linux-library
        path: ViennaRNALink/LibraryResources/Linux-x86-64/

    - name: Download Windows builds
      uses: actions/download-artifact@v4
      with:
        name: windows-library
        path: ViennaRNALink/LibraryResources/Windows-x86-64
    
    - name: Upload final paclet
      uses: actions/upload-artifact@v4
      with:
        name: ViennaRNALink
        path: ViennaRNALink/
        if-no-files-found: error
