name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: robinraju/release-downloader@v1.10
  #       with:
  #         repository: ViennaRNA/ViennaRNA
  #         tag: v2.6.4

  #     - name: Unpack ViennaRNA release
  #       run: unzip -q ViennaRNA-2.6.4.zip

  #     - name: Run configure
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         ./configure --prefix=/home/runner/work/ViennaRNALink/ViennaRNALink/build --without-perl --without-python --without-swig --without-doc-html --without-doc-pdf --without-doc --enable-shared=yes --enable-static=no --enable-universal-binary=yes

  #     - name: Run make
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         make

  #     - name: Run make install
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         make install

  #     - name: Build wrapper library
  #       run: |
  #         cd build/lib
  #         echo "void dummy() {}" >> dummy.c
  #         clang++ dummy.c --shared -Wl,--whole-archive,libRNA.a -Wl,--no-whole-archive -o libRNA.so

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: linux-library
  #         path: build/lib/libRNA.so
  
  # build-macos:
  #   runs-on: macos-latest
    
  #   steps:
  #     - uses: robinraju/release-downloader@v1.10
  #       with:
  #         repository: ViennaRNA/ViennaRNA
  #         tag: v2.6.4

  #     - name: Test
  #       run: pwd

  #     - name: Unpack ViennaRNA release
  #       run: unzip -q ViennaRNA-2.6.4.zip

  #     - name: Run configure
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         ./configure --prefix=/Users/runner/work/ViennaRNALink/ViennaRNALink/build --without-perl --without-python --without-swig --without-doc-html --without-doc-pdf --without-doc --enable-shared=yes --enable-static=no --enable-universal-binary=yes

  #     - name: Run make
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         make

  #     - name: Run make install
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         make install

  #     - name: Build wrapper library
  #       run: |
  #         cd build/lib
  #         echo "void dummy() {}" >> dummy.c
  #         clang++ dummy.c --shared -Wl,-force_load,libRNA.a -o libRNA.dylib

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: macos-library
  #         path: build/lib/libRNA.dylib

  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - shell: bash
  #       run: choco install anaconda3
        
  #     - shell: bash
  #       run: ls C:\tools\anaconda3

  #     - shell: bash
  #       run: C:\tools\anaconda3\conda create -n viennarna-env

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Download installer
        shell: bash
        run: curl --output Install-ViennaRNA-2.6.2_64bit.exe https://www.tbi.univie.ac.at/RNA/download/win/windows/Install-ViennaRNA-2.6.2_64bit.exe

      - name: Run installer
        run: .\Install-ViennaRNA-2.6.2_64bit.exe

      - run: ls

      - run: RNAfold --version

      - run: $Env:Path

      - shell: bash
        run: ls "C:\Program Files\"

  # build-windows:
  #   runs-on: windows-latest
    
  #   steps:
  #     - name: Install Cygwin Action
  #       uses: cygwin/cygwin-install-action@v4

  #     # Suggested with the Cygwin action for getting windows-compatible linebreaks from git.
  #     - run: git config --global core.autocrlf input
            
  #     - uses: robinraju/release-downloader@v1.10
  #       with:
  #         repository: ViennaRNA/ViennaRNA
  #         tag: v2.6.4

  #     - name: Unpack ViennaRNA release
  #       shell: cmd
  #       run: unzip -q ViennaRNA-2.6.4.zip

  #     - name: Run configure
  #       shell: cmd
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         ls
  #         C:\cygwin\bin\bash ./configure --prefix=D:\a\ViennaRNALink\ViennaRNALink\build --without-perl --without-python --without-swig --without-doc-html --without-doc-pdf --without-doc --enable-shared=yes --enable-static=no --disable-pthreads

  #     - name: Run make
  #       shell: cmd
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         C:\cygwin\bin\bash make

  #     - name: Run make install
  #       shell: cmd
  #       run: |
  #         cd ViennaRNA-2.6.4
  #         C:\cygwin\bin\bash make install
