name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download ViennaRNA release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: ViennaRNA/ViennaRNA
          tag: v2.6.4

      - name: Run a one-line script
        run: |
          gunzip ViennaRNA-2.6.4.tar.gz

      - name: Run a multi-line script
        run: ls
